### ISSUE TITLE
Investigate using circle ci

### ISSUE THREAD

**Issue by holdenk** [nteract/coffee_boat#26]
@rgbkrk found another project testing Spark integrations with circle ci which might be a good starting point. See https://github.com/tribbloid/spookystuff/blob/master/.circleci/config.yml

**Comment by rgbkrk** [comment]
One other cool thing about circle CI is that you can attach more than one image for other services: https://circleci.com/docs/2.0/executor-types/#using-multiple-docker-images

**Comment by holdenk** [comment]
That would be really great for testing that we work with Spark+K8 after K8 is merged in Spark 2.3 (although the K8 stuff has it's own solution to req parsing so we'd need some code changes too).

**Comment by holdenk** [comment]
Awesome @willingc got this of the ground. I'll create a follow up.
